(()=>{'use strict';
const lang=document.documentElement.lang==='fa'?'fa':'en';
const api=async(path,payload)=>{const response=await fetch(path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload),credentials:'same-origin'});let body={};try{body=await response.json()}catch{}if(!response.ok)throw new Error(body.error||body.title||`HTTP ${response.status}`);return body};
const note=(message)=>{const el=document.querySelector('#toast');if(el){el.textContent=message;el.classList.add('show');setTimeout(()=>el.classList.remove('show'),5500)}else alert(message)};
// Capture before the original demo handlers; only take ownership when explicitly running from the ASP.NET Core host.
if(!window.ASHKAN_LIVE_API)return;
const reservation=document.querySelector('#reservationForm');
reservation?.addEventListener('submit',async(e)=>{e.preventDefault();e.stopImmediatePropagation();const b=reservation.querySelector('[type=submit]');const d=new FormData(reservation);const data={name:String(d.get('name')||'').trim(),phone:String(d.get('phone')||'').trim(),date:String(d.get('date')||''),time:String(d.get('time')||''),guests:Number(d.get('people')||2),note:String(d.get('note')||'').trim()};if(!reservation.reportValidity())return;b.disabled=true;try{const result=await api('/api/reservations',data);note(lang==='fa'?`درخواست رزرو شماره ${result.id} ثبت شد؛ هنوز تأیید نشده است.`:`Request #${result.id} received. Your table is NOT yet confirmed.`);reservation.reset();document.querySelector('#reservationModal').hidden=true}catch(err){note(lang==='fa'?'ثبت درخواست ناموفق بود؛ دوباره تلاش کنید.':'Could not send your request. Please retry.')}finally{b.disabled=false}},true);
const chat=document.querySelector('#chatForm');
chat?.addEventListener('submit',async(e)=>{e.preventDefault();e.stopImmediatePropagation();const input=document.querySelector('#chatInput'),v=input?.value.trim();if(!v)return;input.value='';const box=document.querySelector('#chatMessages');const add=(t,cls)=>{const el=document.createElement('p');el.className=cls;el.textContent=t;box.append(el);box.scrollTop=box.scrollHeight;return el};add(v,'user-message');const pending=add(lang==='fa'?'در حال پاسخ…':'Thinking…','bot-message');try{const data=await api('/api/assistant',{message:v.slice(0,500),language:lang});pending.textContent=data.answer||'No response'}catch{pending.textContent=lang==='fa'?'دستیار هوشمند در دسترس نیست؛ لطفاً بعداً تلاش کنید.':'AI assistant is unavailable. Please try again later.'}},true);
})();