(()=>{'use strict';
const $=id=>document.getElementById(id), api=async(url,opts={})=>{const r=await fetch(url,{credentials:'same-origin',...opts,headers:{'Content-Type':'application/json',...(opts.headers||{})}});if(!r.ok)throw Error('Request failed ('+r.status+')');return r.json()};
const text=(v)=>String(v??'');const node=(tag,value)=>{const e=document.createElement(tag);e.textContent=text(value);return e};
let roles=[];const can=(...r)=>roles.some(x=>r.includes(x));
function visible(){const admin=can('Admin'),kitchen=can('Admin','Manager','Kitchen'),reception=can('Admin','Manager','Reception');document.querySelectorAll('[data-access]').forEach(el=>{const role=el.dataset.access;el.hidden=role==='admin'?!admin:role==='kitchen'?!kitchen:!reception});}
function row(tbody,values){const tr=document.createElement('tr');values.forEach(v=>tr.append(node('td',v)));tbody.append(tr);return tr}
async function load(){if(can('Admin')){try{const s=await api('/api/admin/summary');for(const [key,id] of [['reservations','total'],['pending','pending'],['confirmed','confirmed'],['activeDishes','dishes']])$(id).textContent=s[key]??'—'}catch{}}if(can('Admin','Manager','Reception')){try{const rs=await api('/api/admin/reservations');$('reservations').replaceChildren();for(const r of rs){const tr=row($('reservations'),[r.id,r.name,r.phone,r.date,r.time,r.guests,r.status]);const td=node('td','');const select=document.createElement('select');for(const status of ['Pending','Confirmed','Rejected']){const op=node('option',status);op.value=status;op.selected=status===r.status;select.append(op)}const b=node('button','Save');b.onclick=async()=>{try{await api('/api/admin/reservations/'+r.id,{method:'PATCH',body:JSON.stringify({status:select.value})});$('message').textContent='Reservation updated';await load()}catch(e){$('message').textContent=e.message}};td.append(select,b);tr.append(td)}}catch(e){$('message').textContent=e.message}}
if(can('Admin')){try{const menu=await api('/api/admin/menu');$('menuRows').replaceChildren();for(const m of menu)row($('menuRows'),[m.id,m.nameEn,m.nameFa,m.usd,m.toman,m.active?'Yes':'No','—'])}catch{}}}
async function session(){try{const me=await api('/api/admin/me');roles=me.roles||me.Roles||[];$('loginPanel').hidden=true;$('workspace').hidden=false;visible();await load()}catch{$('loginPanel').hidden=false;$('workspace').hidden=true;document.querySelectorAll('[data-access]').forEach(x=>x.hidden=true)}}
$('login')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/login',{method:'POST',body:JSON.stringify({email:f.get('email'),password:f.get('password')})});await session()}catch{$('message').textContent='Invalid credentials or server unavailable'}});
$('logout')?.addEventListener('click',async()=>{try{await api('/api/admin/logout',{method:'POST'})}finally{location.reload()}});
$('refresh')?.addEventListener('click',load);
$('language')?.addEventListener('click',()=>{const fa=document.documentElement.lang!=='fa';document.documentElement.lang=fa?'fa':'en';document.documentElement.dir=fa?'rtl':'ltr';document.querySelectorAll('[data-en][data-fa]').forEach(x=>x.textContent=x.dataset[fa?'fa':'en']);$('language').textContent=fa?'English':'فارسی'});
$('newDish')?.addEventListener('submit',async e=>{e.preventDefault();const f=new FormData(e.currentTarget);try{await api('/api/admin/menu',{method:'POST',body:JSON.stringify({nameEn:f.get('nameEn'),nameFa:f.get('nameFa'),usd:Number(f.get('usd')),toman:Number(f.get('toman')),active:true})});e.currentTarget.reset();await load()}catch(err){$('message').textContent=err.message}});
session();})();